import type { Agent, Booking, Property } from "@/types";

/** HOUSE listings — prices in PKR */
export const MOCK_PROPERTIES: Property[] = [
  {
    _id: "1",
    title: "HOUSE Skyline Penthouse",
    description:
      "Exclusively on HOUSE — luxury Clifton penthouse with Arabian Sea views, premium finishes, and smart home features. Ideal for HOUSE clients seeking elite city living.",
    price: 686000000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    type: "penthouse",
    location: "Clifton Block 4",
    city: "Karachi",
    images: ["/properties/house1.png"],
    amenities: ["Pool", "Gym", "Concierge", "Smart Home", "Rooftop Terrace"],
    featured: true,
    status: "available",
    agentId: "a1",
    coordinates: { lat: 24.8138, lng: 67.0299 },
    createdAt: "2025-01-15",
  },
  {
    _id: "2",
    title: "HOUSE Clifton Sea View Villa",
    description:
      "A flagship HOUSE listing in DHA Phase 8 — private garden, infinity pool, and full client support for viewings and booking through HOUSE.",
    price: 1064000000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    type: "villa",
    location: "DHA Phase 8",
    city: "Karachi",
    images: ["/properties/house2.png"],
    amenities: ["Private Garden", "Infinity Pool", "Wine Cellar", "Home Theater"],
    featured: true,
    status: "available",
    agentId: "a2",
    coordinates: { lat: 24.7742, lng: 67.0581 },
    createdAt: "2025-02-01",
  },
  {
    _id: "3",
    title: "HOUSE Modern Glass Apartment",
    description:
      "Listed on HOUSE for discerning clients — minimalist Bahria Town apartment with smart home integration and HOUSE 3D virtual tour included.",
    price: 249200000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    type: "apartment",
    location: "Bahria Town Karachi",
    city: "Karachi",
    images: ["/properties/house3.png"],
    amenities: ["Smart Home", "Gym", "Parking", "Balcony"],
    featured: true,
    status: "available",
    agentId: "a1",
    coordinates: { lat: 25.0122, lng: 67.3105 },
    createdAt: "2025-02-10",
  },
  {
    _id: "4",
    title: "HOUSE Heritage Townhouse",
    description:
      "HOUSE presents this restored PECHS townhouse — classic charm with modern amenities, verified by our client services team.",
    price: 462000000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    type: "house",
    location: "PECHS Block 2",
    city: "Karachi",
    images: ["/properties/house4.png"],
    amenities: ["Garden", "Fireplace", "Garage", "Study Room"],
    featured: false,
    status: "available",
    agentId: "a3",
    coordinates: { lat: 24.8676, lng: 67.0641 },
    createdAt: "2025-03-01",
  },
  {
    _id: "5",
    title: "HOUSE Scheme 33 Farmhouse",
    description:
      "Exclusive HOUSE estate listing — spacious farmhouse with spa, gardens, and private tours arranged for registered HOUSE clients.",
    price: 1176000000,
    bedrooms: 6,
    bathrooms: 5,
    area: 5200,
    type: "villa",
    location: "Scheme 33",
    city: "Karachi",
    images: ["/properties/house5.png"],
    amenities: ["Spa", "Sauna", "Chef Kitchen", "Large Garden", "Security"],
    featured: true,
    status: "available",
    agentId: "a2",
    coordinates: { lat: 24.9492, lng: 67.1536 },
    createdAt: "2025-03-15",
  },
  {
    _id: "6",
    title: "HOUSE Gulshan Urban Loft",
    description:
      "Affordable luxury on HOUSE — industrial-chic loft for young professionals and investors, with instant HOUSE booking for viewings.",
    price: 145600000,
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    type: "condo",
    location: "Gulshan-e-Iqbal",
    city: "Karachi",
    images: ["/properties/house6.png"],
    amenities: ["Rooftop Access", "Exposed Brick", "High Ceilings"],
    featured: false,
    status: "available",
    agentId: "a3",
    coordinates: { lat: 24.9142, lng: 67.0822 },
    createdAt: "2025-04-01",
  },
];

export const MOCK_AGENTS: Agent[] = [
  {
    _id: "a1",
    name: "Aisha Khan",
    email: "aisha@house.com",
    phone: "+92 300 1234567",
    avatar: "/clients/client1.png",
    bio: "Lead HOUSE agent for Clifton & Bahria — 12+ years helping clients secure premium Karachi homes.",
    propertiesSold: 156,
    rating: 4.9,
  },
  {
    _id: "a2",
    name: "Hassan Malik",
    email: "hassan@house.com",
    phone: "+92 321 2345678",
    avatar: "/clients/client2.png",
    bio: "HOUSE DHA specialist — trusted by 200+ clients for villas, penthouses, and investment properties.",
    propertiesSold: 203,
    rating: 4.95,
  },
  {
    _id: "a3",
    name: "Zara Sheikh",
    email: "zara@house.com",
    phone: "+92 333 3456789",
    avatar: "/clients/client3.png",
    bio: "HOUSE heritage homes expert — guides clients through PECHS, Gulshan, and unique Karachi properties.",
    propertiesSold: 98,
    rating: 4.85,
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    _id: "b1",
    propertyId: "1",
    userId: "u1",
    name: "Ahmed Khan",
    email: "ahmed@email.com",
    phone: "+92 300 1110101",
    date: "2025-05-10",
    status: "confirmed",
    createdAt: "2025-04-28",
  },
  {
    _id: "b2",
    propertyId: "2",
    userId: "u2",
    name: "Fatima Ali",
    email: "fatima@email.com",
    phone: "+92 321 1110102",
    date: "2025-05-15",
    status: "pending",
    createdAt: "2025-05-01",
  },
  {
    _id: "b3",
    propertyId: "3",
    userId: "u3",
    name: "Hassan Raza",
    email: "hassan@email.com",
    phone: "+92 333 1110103",
    date: "2025-05-20",
    status: "confirmed",
    createdAt: "2025-05-05",
  },
];
